M48
; DRILL file {KiCad 7.0.9} date Thu Apr 10 13:05:30 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-10T13:05:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X167.386Y-72.51
X167.386Y-75.01
X172.386Y-80.01
X177.386Y-72.51
X177.386Y-75.01
T0
M30
